/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schedule */
        get: operations["schedule_api_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FreshnessResponse */
        FreshnessResponse: {
            /** Stale */
            stale: boolean;
            /** Reason */
            reason?: string | null;
            /** Checkedat */
            checkedAt?: string | null;
            /** Lastsuccessat */
            lastSuccessAt?: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
        };
        /** MeetingResponse */
        MeetingResponse: {
            /**
             * Status
             * @default scheduled
             * @enum {string}
             */
            status: "scheduled" | "cancelled";
            /** Publicationversion */
            publicationVersion: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Competition */
            competition: string;
            /** Season */
            season: number;
            /** Circuit */
            circuit: string;
            /** Startdate */
            startDate: string;
            /** Enddate */
            endDate: string;
            /** Sourceurl */
            sourceUrl: string;
            /** Retrievedat */
            retrievedAt: string;
            /** Round */
            round?: number | null;
            /** Roundid */
            roundId?: string | null;
            /** Eventtimezone */
            eventTimezone?: string | null;
            /** Sessions */
            sessions?: components["schemas"]["SessionResponse"][];
        };
        /** ScheduleResponse */
        ScheduleResponse: {
            /** Meetings */
            meetings: components["schemas"]["MeetingResponse"][];
            freshness?: components["schemas"]["FreshnessResponse"] | null;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "completed" | "cancelled";
            start: components["schemas"]["TimeResponse"];
            end: components["schemas"]["TimeResponse"] | null;
        };
        /** TimeResponse */
        TimeResponse: {
            /** Local */
            local: string;
            /** Offset */
            offset: string | null;
            /** Zone */
            zone: string | null;
            /** Instant */
            instant: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    schedule_api_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
        };
    };
}
