/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schedule */
        get: operations["schedule_api_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assistant Session */
        post: operations["assistant_session_api_assistant_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assistant Message */
        post: operations["assistant_message_api_assistant_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Assistant Reset */
        delete: operations["assistant_reset_api_assistant_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssistantAnswer */
        AssistantAnswer: {
            /** Text */
            text: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * Classification
             * @enum {string}
             */
            classification: "stated" | "derived" | "unsupported";
            /** Displaytimezone */
            displayTimeZone: string;
            /** Publicationversion */
            publicationVersion: string | null;
            /** Freshness */
            freshness: {
                [key: string]: unknown;
            };
        };
        /** AssistantMessage */
        AssistantMessage: {
            /** Message */
            message: string;
            /** Displaytimezone */
            displayTimeZone: string;
        };
        /** AssistantSessionResponse */
        AssistantSessionResponse: {
            /** Sessiontoken */
            sessionToken: string;
            /** Available */
            available: boolean;
        };
        /** CandidateLayout */
        CandidateLayout: {
            /** Identity */
            identity: string;
            /** Name */
            name: string;
            /** Length Km */
            length_km?: number | null;
        };
        /** CandidatePlace */
        CandidatePlace: {
            /** Identity */
            identity: string;
            /** Name */
            name: string;
        };
        /** Citation */
        Citation: {
            /** Id */
            id: string;
            /** Iri */
            iri: string;
            /** Title */
            title: string;
            /** Sourceurl */
            sourceUrl: string;
            /** Retrievedat */
            retrievedAt: string | null;
        };
        /** CoverageAssessment */
        CoverageAssessment: {
            /**
             * State
             * @enum {string}
             */
            state: "complete" | "incomplete" | "unassessed";
            /**
             * Activity
             * @enum {string}
             */
            activity: "present" | "empty" | "unknown";
            /** Reason */
            reason: string;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
        };
        /** FieldAssertion */
        FieldAssertion: {
            /** Field */
            field: string;
            /** Value */
            value: string;
            /** Source Url */
            source_url: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Locator */
            locator: string;
            /** Rule */
            rule: string;
            /**
             * Preferred
             * @default false
             */
            preferred: boolean;
            /** Response Sha256 */
            response_sha256?: string | null;
            translation?: components["schemas"]["TranslationRecord"] | null;
            /** Subject Identity */
            subject_identity?: string | null;
            /** Effective Local */
            effective_local?: string | null;
        };
        /** FreshnessResponse */
        FreshnessResponse: {
            /** Stale */
            stale: boolean;
            /** Reason */
            reason?: string | null;
            /** Checkedat */
            checkedAt?: string | null;
            /** Lastsuccessat */
            lastSuccessAt?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceFreshnessResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
        };
        /** MeetingResponse */
        MeetingResponse: {
            /**
             * Status
             * @default scheduled
             * @enum {string}
             */
            status: "scheduled" | "cancelled";
            /** Publicationversion */
            publicationVersion: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Competition */
            competition: string;
            /** Season */
            season: number;
            /** Circuit */
            circuit: string;
            /** Competitionid */
            competitionId?: string | null;
            /** Circuitid */
            circuitId?: string | null;
            /** Startdate */
            startDate: string;
            /** Enddate */
            endDate: string;
            /** Sourceurl */
            sourceUrl: string;
            /** Retrievedat */
            retrievedAt: string;
            /** Round */
            round?: number | null;
            /** Roundid */
            roundId?: string | null;
            /** Rounds */
            rounds?: components["schemas"]["RoundResponse"][];
            venue?: components["schemas"]["CandidatePlace"] | null;
            layout?: components["schemas"]["CandidateLayout"] | null;
            coverage?: components["schemas"]["CoverageAssessment"] | null;
            /** Kind */
            kind?: ("championship" | "test" | "prologue") | null;
            /** Fieldassertions */
            fieldAssertions?: components["schemas"]["FieldAssertion"][];
            /** Eventtimezone */
            eventTimezone?: string | null;
            /** Sessions */
            sessions?: components["schemas"]["SessionResponse"][];
        };
        /** RoundResponse */
        RoundResponse: {
            /** Id */
            id: string;
            /** Number */
            number: number;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "completed" | "cancelled" | "abandoned";
        };
        /** ScheduleResponse */
        ScheduleResponse: {
            /** Meetings */
            meetings: components["schemas"]["MeetingResponse"][];
            freshness?: components["schemas"]["FreshnessResponse"] | null;
            /** Coverage */
            coverage?: components["schemas"]["SeasonCoverageResponse"][];
        };
        /** SeasonCoverageResponse */
        SeasonCoverageResponse: {
            /**
             * State
             * @enum {string}
             */
            state: "complete" | "incomplete" | "unassessed";
            /**
             * Activity
             * @enum {string}
             */
            activity: "present" | "empty" | "unknown";
            /** Reason */
            reason: string;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /** Competitionid */
            competitionId: string;
            /** Season */
            season: number;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "completed" | "cancelled" | "abandoned";
            start: components["schemas"]["TimeResponse"];
            end: components["schemas"]["TimeResponse"] | null;
            /** Roundid */
            roundId?: string | null;
            /** Durationminutes */
            durationMinutes?: number | null;
            /** Circuitid */
            circuitId?: string | null;
            layout?: components["schemas"]["CandidateLayout"] | null;
        };
        /** SourceFreshnessResponse */
        SourceFreshnessResponse: {
            /** Sourcefamily */
            sourceFamily: string;
            /** Stale */
            stale: boolean;
            /** Reason */
            reason?: string | null;
            /** Checkedat */
            checkedAt?: string | null;
            /** Lastsuccessat */
            lastSuccessAt?: string | null;
        };
        /** TimeResponse */
        TimeResponse: {
            /** Local */
            local: string;
            /** Offset */
            offset: string | null;
            /** Zone */
            zone: string | null;
            /** Instant */
            instant: string | null;
        };
        /** TranslationRecord */
        TranslationRecord: {
            /**
             * Source Language
             * @constant
             */
            source_language: "de";
            /** Method */
            method: string;
            /** Version */
            version: string;
            /**
             * Translated At
             * Format: date-time
             */
            translated_at: string;
            /**
             * Review State
             * @constant
             */
            review_state: "accepted-standing-poc";
            /** Reviewer */
            reviewer: string;
            /** Authorization */
            authorization: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    schedule_api_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
        };
    };
    assistant_session_api_assistant_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantSessionResponse"];
                };
            };
        };
    };
    assistant_message_api_assistant_messages_post: {
        parameters: {
            query?: never;
            header: {
                "x-assistant-session": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_reset_api_assistant_session_delete: {
        parameters: {
            query?: never;
            header: {
                "x-assistant-session": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
